### ISSUE TITLE
css next tips

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#123]
```css
/* var */

:root {
  --mainColor: red;
}

a {
  color: var(--mainColor);
}

/* nesting */

a {
  /* direct nesting (& MUST be the first part of selector)*/
  & span {
    color: white;
  }

  /* @nest rule (for complex nesting) */
  @nest span & {
    color: blue;
  }

  /* media query automatic nesting */
  @media (min-width: 30em) {
    color: yellow;
  }
}
```
