### ISSUE TITLE
[scss] - mixin vs extend vs placeholder

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#46]
### @extend

```scss
.one {
  ...;
}

.one-more {
  @extend .one;
  ...;
}
```

* 生成的 css 将同时存在 .one, .one-more;
* 如果此时 .one 不需要直接使用呢?

### placeholder

```scss
%one {
  ...;
}

.one-more {
  @extend %one;
  ...;
}
```

**Comment by coderhaoxin** [comment]
```scss
/**
 * compare to .css, explain the details
 */

/**
 * extend vs placeholder
 *   - placeholder not work in @media
 */

.one {
  display: block;
}

.one-a {
  @extend .one;
  margin: 0 0;
}

.one-b {
  @extend .one;
  margin: 1px 1px;
}

%two {
  display: block;
}

.two-a {
  @extend %two;
  margin: 0 0;
}

.two-b {
  @extend %two;
  margin: 1px 1px;
}

/**
 * mixin vs extend
 */

@mixin m {
  div {
    width: 20px;
  }
}

.e {
  div {
    width: 20px;
  }
}

.c1 {
  @include m();
  height: 30px;
}

.c2 {
  @extend .e;
  height: 30px;
}

```

**Comment by coderhaoxin** [comment]
```css
/**
 * extend vs placeholder
 *   - placeholder not work in @media
 */
.one, .one-a, .one-b {
  display: block; }

.one-a {
  margin: 0 0; }

.one-b {
  margin: 1px 1px; }

.two-a, .two-b {
  display: block; }

.two-a {
  margin: 0 0; }

.two-b {
  margin: 1px 1px; }

/**
 * mixin vs extend
 */
.e div, .c2 div {
  width: 20px; }

.c1 {
  height: 30px; }
  .c1 div {
    width: 20px; }

.c2 {
  height: 30px; }
```

**Comment by coderhaoxin** [comment]
### conclusion

* `extend` and `mixin` are enough

**Comment by coderhaoxin** [comment]
use `mixin`

**Comment by coderhaoxin** [comment]
avoid `naming` conflict!!!

**Comment by coderhaoxin** [comment]
### Referer

* [when-to-use-extend-when-to-use-a-mixin/](http://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/)

**Comment by coderhaoxin** [comment]
```css

/**
 * scss
 */

.one-extend {
  display: flex;
}

.one-more-extend {
  @extend .one-extend;
  margin: auto;
}

%one-placeholder {
  display: flex;
}

.one-more-placeholder {
  @extend %one-placeholder;
  margin: auto;
}

/**
 * css
 */

.one-extend, .one-more-extend {
  display: flex;
}

.one-more-extend {
  margin: auto;
}

.one-more-placeholder {
  display: flex;
}

.one-more-placeholder {
  margin: auto;
}

```
