### ISSUE TITLE
[scss & css] flexbox bug 与 实践

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#50]
* 旧语法不支持 `wrap`

```css
{
  white-space: normal;
  word-break: break-all;
  text-align: center;
}
```
